let handler = m => m

handler.before = function (m) {
  let user = global.db.data.users[m.sender]
        let role = (user.level <= 2) ? 'Warrior ⁵'
          : ((user.level >= 2) && (user.level <= 4)) ? 'Warrior ⁴'
          : ((user.level >= 4) && (user.level <= 6)) ? 'Warrior ³'
          : ((user.level >= 6) && (user.level <= 8)) ? 'Warrior ²'
          : ((user.level >= 8) && (user.level <= 10)) ? 'Warrior ¹'
          : ((user.level >= 10) && (user.level <= 20)) ? 'Elite ⁵'
          : ((user.level >= 20) && (user.level <= 30)) ? 'Elite ⁴'
          : ((user.level >= 30) && (user.level <= 40)) ? 'Elite ³'
          : ((user.level >= 40) && (user.level <= 50)) ? 'Elite ²'
          : ((user.level >= 50) && (user.level <= 60)) ? 'Elite ¹'
          : ((user.level >= 60) && (user.level <= 70)) ? 'Master ⁵' 
          : ((user.level >= 70) && (user.level <= 80)) ? 'Master ⁴' 
          : ((user.level >= 80) && (user.level <= 90)) ? 'Master ³' 
          : ((user.level >= 90) && (user.level <= 100)) ? 'Master ²' 
          : ((user.level >= 100) && (user.level <= 110)) ? 'Master ¹'
          : ((user.level >= 110) && (user.level <= 120)) ? 'Grandmaster ⁵'
          : ((user.level >= 120) && (user.level <= 130)) ? 'Grandmaster ⁴'
          : ((user.level >= 130) && (user.level <= 140)) ? 'Grandmaster ³'
          : ((user.level >= 140) && (user.level <= 150)) ? 'Grandmaster ²'
          : ((user.level >= 150) && (user.level <= 160)) ? 'Grandmaster ¹' 
          : ((user.level >= 160) && (user.level <= 170)) ? 'Epic ⁵' 
          : ((user.level >= 170) && (user.level <= 180)) ? 'Epic ⁴' 
          : ((user.level >= 180) && (user.level <= 190)) ? 'Epic ³' 
          : ((user.level >= 190) && (user.level <= 200)) ? 'Epic ²' 
          : ((user.level >= 200) && (user.level <= 210)) ? 'Epic ¹' 
          : ((user.level >= 210) && (user.level <= 220)) ? 'Legend ⁵'
          : ((user.level >= 220) && (user.level <= 230)) ? 'Legend ⁴'
          : ((user.level >= 230) && (user.level <= 240)) ? 'Legend ³'
          : ((user.level >= 240) && (user.level <= 250)) ? 'Legend ²'
          : ((user.level >= 250) && (user.level <= 260)) ? 'Legend ¹'
          : ((user.level >= 260) && (user.level <= 270)) ? 'Mythic Romawi ⭐1'
          : ((user.level >= 270) && (user.level <= 280)) ? 'Mythic Romawi ⭐5'  
          : ((user.level >= 280) && (user.level <= 290)) ? 'Mythic Romawi ⭐10' 
          : ((user.level >= 290) && (user.level <= 300)) ? 'Mythic Romawi ⭐15' 
          : ((user.level >= 300) && (user.level <= 310)) ? 'Mythic Romawi ⭐24'
          : ((user.level >= 310) && (user.level <= 320)) ? 'Mythical Honor ⭐25'
          : ((user.level >= 320) && (user.level <= 330)) ? 'Mythical Honor ⭐35'
          : ((user.level >= 330) && (user.level <= 340)) ? 'Mythical Honor ⭐40'
          : ((user.level >= 340) && (user.level <= 350)) ? 'Mythical Honor ⭐45'
          : ((user.level >= 350) && (user.level <= 360)) ? 'Mythical Honor ⭐49'
          : ((user.level >= 360) && (user.level <= 370)) ? 'Mythical Glory ⭐50'
          : ((user.level >= 370) && (user.level <= 380)) ? 'Mythical Glory ⭐60'
          : ((user.level >= 380) && (user.level <= 390)) ? 'Mythical Glory ⭐70'
          : ((user.level >= 390) && (user.level <= 400)) ? 'Mythical Glory ⭐80'
          : ((user.level >= 400) && (user.level <= 410)) ? 'Mythical Glory ⭐90'
          : ((user.level >= 410) && (user.level <= 420)) ? 'Mythical Immortal ⭐100'
          : ((user.level >= 420) && (user.level <= 430)) ? 'Mythical Immortal ⭐150'
          : ((user.level >= 430) && (user.level <= 440)) ? 'Mythical Immortal ⭐200'
          : ((user.level >= 440) && (user.level <= 450)) ? 'Mythical Immortal ⭐250'
          : ((user.level >= 450) && (user.level <= 460)) ? 'Mythical Immortal ⭐300'
          : ((user.level >= 460) && (user.level <= 470)) ? 'Mythical Immortal ⭐350'
          : ((user.level >= 470) && (user.level <= 480)) ? 'Mythical Immortal ⭐400'
          : ((user.level >= 480) && (user.level <= 490)) ? 'Mythical Immortal ⭐450' 
          : ((user.level >= 490) && (user.level <= 500)) ? 'Mythical Immortal ⭐500'
          : ((user.level >= 500) && (user.level <= 600)) ? 'Mythical Immortal ⭐550'
          : ((user.level >= 600) && (user.level <= 700)) ? 'Mythical Immortal ⭐600'
          : ((user.level >= 700) && (user.level <= 800)) ? 'Mythical Immortal ⭐650'
          : ((user.level >= 800) && (user.level <= 900)) ? 'Mythical Immortal ⭐700'
          : ((user.level >= 900) && (user.level <= 1000)) ? 'Mythical Immortal ⭐750'
          : '*Dah Tamat!*'
  user.role = role
  return true
}

export default handler